CREATE DATABASE IF NOT EXISTS bookstoredb CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci';

create table if not exists KIND_OF_BOOK (
	KB_ID int not null,
    KB_NAME varchar(50) character set 'utf8' collate 'utf8_unicode_ci' not null,
    PRIMARY KEY(KB_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PUBLISHER (
	PUB_ID INT NOT NULL,
	PUB_NAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
	PUB_ADDRESS VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    PUB_EMAIL VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    PUB_PHONE INT,
	PRIMARY KEY (PUB_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS AUTHORS (
	A_ID INT NOT NULL,
	A_NAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
	A_NOTES VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (A_ID)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS BOOK (
 B_ID INT NOT NULL,
 B_NAME VARCHAR(45) NOT NULL,
 B_AUTHORS_ID INT NOT NULL,
 B_PUBLISHER_ID INT NOT NULL,
 B_COST INT NOT NULL,
 KIND_OF_BOOK_KB_ID INT NOT NULL,
 B_PUBLISHING_YEAR INT,
 PRIMARY KEY (B_ID),
 INDEX fk_BOOK_KIND_OF_BOOK_idx (KIND_OF_BOOK_KB_ID ASC),
 CONSTRAINT fk_BOOK_KIND_OF_BOOK
 FOREIGN KEY (KIND_OF_BOOK_KB_ID)
 REFERENCES KIND_OF_BOOK (KB_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION
 
 )ENGINE = InnoDB;
 
CREATE TABLE IF NOT EXISTS SUPPLIER (
	SUP_ID INT NOT NULL,
	SUP_NAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
	SUP_ADDRESS VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    SUP_EMAIL VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    SUP_PHONE INT,
	PRIMARY KEY (SUP_ID)
) ENGINE = InnoDB;
 
 
 CREATE TABLE IF NOT EXISTS WAREHOUSE_BILLS (
	WB_ID INT NOT NULL,
	WB_DATE DATETIME NOT NULL,
	WB_BOOK_ID INT NOT NULL,
	WB_SUPPLIER_ID INT NOT NULL,
	WB_BOOK_NUMBER INT,
	PRIMARY KEY (WB_ID),

CONSTRAINT fk_WB_SUPPLIER_ID
FOREIGN KEY (WB_SUPPLIER_ID)
REFERENCES SUPPLIER (SUP_ID)
ON DELETE CASCADE
ON UPDATE CASCADE
 ) ENGINE = InnoDB;
 
 CREATE TABLE IF NOT EXISTS PUBLISHER_has_BOOK (
	PUBLISHER_PUB_ID INT NOT NULL,
	BOOK_B_ID INT NOT NULL,
 PRIMARY KEY (PUBLISHER_PUB_ID, BOOK_B_ID),
 INDEX fk_PUBLISHER_has_BOOK_BOOK_idx (BOOK_B_ID ASC),
 INDEX fk_PUBLISHER_has_BOOK_PUBLISHER_idx (PUBLISHER_PUB_ID ASC),
 
 CONSTRAINT fk_PUBLISHER_has_BOOK_PUBLISHER
 FOREIGN KEY (PUBLISHER_PUB_ID)
 REFERENCES PUBLISHER (PUB_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION,
 
 CONSTRAINT fk_PUBLISHER_has_BOOK_BOOK
 FOREIGN KEY (BOOK_B_ID)
 REFERENCES BOOK (B_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION
 
 ) ENGINE = InnoDB;
 CREATE TABLE IF NOT EXISTS BOOK_has_WAREHOUSE_BILLS (
	WAREHOUSE_BILLS_WB_ID INT NOT NULL,
	BOOK_B_ID INT NOT NULL,
 PRIMARY KEY (WAREHOUSE_BILLS_WB_ID, BOOK_B_ID),
 
 INDEX fk_BOOK_has_WAREHOUSE_BILLS_BOOK_idx (BOOK_B_ID ASC),
 INDEX fk_BOOK_has_WAREHOUSE_BILLS_WAREHOUSE_BILLS_idx (WAREHOUSE_BILLS_WB_ID ASC),
 
 CONSTRAINT fk_BOOK_has_WAREHOUSE_BILLS_WAREHOUSE_BILLS
 FOREIGN KEY (WAREHOUSE_BILLS_WB_ID)
 REFERENCES WAREHOUSE_BILLS (WB_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION,
 
 CONSTRAINT fk_BOOK_has_WAREHOUSE_BILLS_BOOK
 FOREIGN KEY (BOOK_B_ID)
 REFERENCES BOOK (B_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION
 
 ) ENGINE = InnoDB;
 
 CREATE TABLE IF NOT EXISTS AUTHORS_has_BOOK (
	AUTHORS_A_ID INT NOT NULL,
	BOOK_B_ID INT NOT NULL,
 PRIMARY KEY (AUTHORS_A_ID, BOOK_B_ID),
 INDEX fk_AUTHORS_has_BOOK_BOOK_idx (BOOK_B_ID ASC),
 INDEX fk_AUTHORS_has_BOOK_AUTHORS_idx (AUTHORS_A_ID ASC),
 
 CONSTRAINT fk_AUTHORS_has_BOOK_AUTHORS
 FOREIGN KEY (AUTHORS_A_ID)
 REFERENCES AUTHORS (A_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION,
 
 CONSTRAINT fk_AUTHORS_has_BOOK_BOOK
 FOREIGN KEY (BOOK_B_ID)
 REFERENCES BOOK (B_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION
 
 ) ENGINE = InnoDB;
 
 CREATE TABLE IF NOT EXISTS CUSTOMER (
	CUS_ID INT NOT NULL,
	CUS_NAME VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
	CUS_ADDRESS VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    CUS_EMAIL VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
    CUS_PHONE INT,
	PRIMARY KEY (CUS_ID)
) ENGINE = InnoDB;

 CREATE TABLE IF NOT EXISTS SALES_BILLS (
	SB_ID INT NOT NULL,
	SB_DATE DATETIME NOT NULL,
	SB_BOOK_ID INT NOT NULL,
	SB_BOOK_NUMBER INT,
    SB_CUS_ID INT,
	PRIMARY KEY (SB_ID),
    
    CONSTRAINT fk_SB_CUS_ID
	FOREIGN KEY (SB_CUS_ID)
	REFERENCES CUSTOMER (CUS_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)ENGINE = InnoDB;
    
CREATE TABLE IF NOT EXISTS SALES_BILLS_has_BOOK (
	SALES_BILLS_SB_ID INT NOT NULL,
	BOOK_B_ID INT NOT NULL,
 PRIMARY KEY (SALES_BILLS_SB_ID, BOOK_B_ID),
 INDEX fk_SALES_BILLS_has_BOOK_BOOK_idx (BOOK_B_ID ASC),
 INDEX fk_SALES_BILLS_has_BOOK_SALES_BILLS_idx (SALES_BILLS_SB_ID ASC),
 
 CONSTRAINT fk_SALES_BILLS_has_BOOK_SALES_BILLS
 FOREIGN KEY (SALES_BILLS_SB_ID)
 REFERENCES SALES_BILLS (SB_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION,
 
 CONSTRAINT fk_SALES_BILLS_has_BOOK_BOOK
 FOREIGN KEY (BOOK_B_ID)
 REFERENCES BOOK (B_ID)
 ON DELETE NO ACTION
 ON UPDATE NO ACTION
    
)ENGINE = InnoDB;    
 


